export const theme = {
    common: {
        primaryColor: '#5772FF',
        primaryColorHover: '#708BFF',
        primaryColorPressed: '#708BFF',
        primaryColorSuppl: '#148be1',
        bodyColor: '#101010',
        cardColor: '#101010',
        popoverColor: '#101010',
        modalColor: '#101010',
        tableColor: '#101010',
        textColorBase: 'var(--jm-accent-7)',
        textColor1: 'var(--jm-accent-7)',
        textColor2: 'var(--jm-accent-7)',
        textColor3: 'var(--jm-accent-7)',
    },
    Button: {
        colorPrimary: 'var(--jm-primary-1)',
        textColorPrimary: 'var(--jm-accent-7)',
        textColorHoverPrimary: 'var(--jm-accent-7)',
        textColorPressedPrimary: 'var(--jm-accent-7)',
        textColorFocusPrimary: 'var(--jm-accent-7)',
        colorPressedPrimary: 'var(--jm-primary-1)',
        colorHoverPrimary: 'var(--jm-primary-2)',
        colorDisabledPrimary: 'var(--jm-primary-1)',
        borderPrimary: '1px solid var(--jm-primary-1)',
        borderHoverPrimary: '1px solid var(--jm-primary-2)',
        borderPressedPrimary: '1px solid var(--jm-primary-1)',
        borderFocusPrimary: '1px solid var(--jm-primary-1)',
        borderDisabledPrimary: '1px solid var(--jm-primary-1)',
        fontWeight: '400',
        heightSmall: '28px',
        fontSizeSmall: '12px',
        paddingSmall: '0 8px',
        heightMedium: '34px',
        paddingMedium: '5px 18px',
        fontSizeMedium: '12px',
        heightLarge: '40px',
        paddingLarge: '9px 26px',
        fontSizeLarge: '14px',
        colorWarning: 'var(--jm-primary-1)',
        colorHoverWarning: 'var(--jm-primary-2)',
        colorPressedWarning: 'var(--jm-primary-1)',
        textColorWarning: 'var(--jm-accent-7)',
        textColorHoverWarning: 'var(--jm-accent-7)',
        borderWarning: '1px solid var(--jm-primary-1)',
        borderHoverWarning: '1px solid var(--jm-primary-1)',
        colorInfo: 'var(--jm-primary-1)',
        colorHoverInfo: 'var(--jm-primary-2)',
        textColorInfo: 'var(--jm-accent-7)',
        textColorHoverInfo: 'var(--jm-accent-7)',
        borderInfo: '1px solid var(--jm-primary-1)',
        borderHoverInfo: '1px solid var(--jm-primary-1)',
        colorSuccess: 'var(--jm-primary-1)',
        colorHoverSuccess: 'var(--jm-primary-2)',
        textColorSuccess: 'var(--jm-accent-7)',
        textColorHoverSuccess: 'var(--jm-accent-7)',
        borderSuccess: '1px solid var(--jm-primary-1)',
        borderHoverSuccess: '1px solid var(--jm-primary-1)',
        colorError: 'var(--jm-primary-1)',
        colorHoverError: 'var(--jm-primary-2)',
        textColorError: 'var(--jm-accent-7)',
        textColorHoverError: 'var(--jm-accent-7)',
        borderError: '1px solid var(--jm-primary-1)',
        borderHoverError: '1px solid var(--jm-primary-1)',
        textColorDisabled: 'var(--jm-accent-7)',
        textColorDisabledPrimary: 'var(--jm-accent-7)',
    },
    Select: {
        menuBoxShadow: '0 0 1px var(--jm-accent-5)',
        peers: {
            InternalSelection: {
                fontWeight: '400',
                fontSizeMedium: '13px',
                placeholderColor: 'var(--jm-accent-4)',
                borderRadius: '4px',
                color: 'var(--jm-theme)',
                textColor: 'var(--jm-accent-7)',
                border: '1px solid var(--jm-accent-2)',
                paddingSingle: '10px',
            },
            InternalSelectMenu: {
                fontWeight: '400',
                optionFontSizeMedium: '13px',
                optionHeightMedium: '34px',
                color: 'var(--jm-accent-1)',
                optionTextColorHover: 'var(--jm-accent-7)',
                optionTextColor: 'var(--jm-accent-7)',
                border: '1px solid var(--jm-accent-2)',
                borderRadius: '4px',
            },
        },
    },
    Input: {
        heightMedium: '34px',
        fontSizeMedium: '12px',
        borderRadius: '4px',
        border: '1px solid var(--jm-accent-3)',
        color: 'var(--jm-theme)',
        textColor: 'var(--jm-accent-7)',
        placeholderColor: 'var(--jm-accent-4)',
        caretColor: 'var(--jm-primary-1)',
        colorFocus: 'var(--jm-theme)',
    },
    InputNumber: {
        heightMedium: '34px',
        fontSizeMedium: '12px',
    },
    Dialog: {
        color: 'var(--jm-theme)',
        iconColorError: 'var(--jm-error-color)',
        iconColorWarning: 'var(--jm-warning-color)',
        iconColorSuccess: 'var(--jm-success-color)',
        iconColorInfo: 'var(--jm-primary-1)',
    },
    Message: {
        iconColorSuccess: 'var(--jm-success-color)',
        iconColorWarning: 'var(--jm-warning-color)',
        iconColorError: 'var(--jm-error-color)',
        iconColorInfo: 'var(--jm-primary-1)',
        borderRadius: '8px',
        textColor: 'var(--jm-primary-1)',
    },
    Card: {
        color: 'var(--jm-theme)',
        borderColor: 'var(--jm-accent-2)',
        textColor: 'var(--jm-accent-7)',
        titleTextColor: 'var(--jm-accent-7)',
    },
    Modal: {
        color: 'var(--jm-theme)',
        textColor: 'var(--jm-accent-7)',
        boxShadow: '0 0 20px rgba(0,0,0,0.5)',
    },
    Switch: {
        railColor: 'var(--jm-accent-3)',
        railColorActive: 'var(--jm-primary-1)',
        loadingColor: 'var(--jm-primary-1)',
    },
    Tooltip: {
        color: 'rgba(57,57,57,0.95)',
        padding: '4px 8px',
        borderRadius: '4px',
        boxShadow: '0 2px 4px 0 rgba(0, 0, 0, 0.25)',
    },
    Dropdown: {
        color: 'var(--jm-theme)',
        optionTextColor: 'var(--jm-accent-7)',
        dividerColor: 'var(--jm-accent-2)',
    },
    Tag: {
        color: 'var(--jm-accent-1)',
        textColor: 'var(--jm-accent-7)',
        borderColor: 'var(--jm-accent-3)',
    },
    Steps: {
        headerTextColorProcess: 'var(--jm-accent-7)',
        headerTextColorFinish: 'var(--jm-accent-6)',
        headerTextColorWait: 'var(--jm-accent-4)',
        indicatorColorProcess: 'var(--jm-primary-1)',
        indicatorTextColorProcess: 'var(--jm-accent-7)',
        indicatorBorderColorProcess: 'var(--jm-primary-1)',
        indicatorColorFinish: 'var(--jm-primary-1)',
        splitorColorProcess: 'var(--jm-primary-1)',
        descriptionTextColorProcess: 'var(--jm-accent-5)',
        descriptionTextColorFinish: 'var(--jm-accent-5)',
        descriptionTextColorWait: 'var(--jm-accent-4)',
    },
    Progress: {
        fillColor: 'var(--jm-primary-1)',
        railColor: 'var(--jm-accent-2)',
    },
    Form: {
        labelTextColor: 'var(--jm-accent-6)',
        feedbackTextColorError: 'var(--jm-error-color)',
    },
    Spin: {
        color: 'var(--jm-primary-1)',
    },
    Result: {
        titleTextColor: 'var(--jm-accent-7)',
        textColor: 'var(--jm-accent-6)',
    },
}
